regions:
  - ap-southeast-1
  - us-east-1
  - ap-southeast-2

blocklist:
  - "999999999999"  # production

accounts:
  "255945442255": {}

resource-types:
  excludes:
    - ACMCertificate
    - ACMPCACertificateAuthority
    - CloudSearchDomain
    - CodeStarProject
    - FMSNotificationChannel
    - FMSPolicy
    - GlobalAccelerator
    - GlobalAcceleratorEndpointGroup
    - GlobalAcceleratorListener
    - MachineLearningBranchPrediction
    - MachineLearningDataSource
    - MachineLearningEvaluation
    - MachineLearningMLModel
    - MobileProject
    - OpsWorksApp
    - OpsWorksCMBackup
    - OpsWorksCMServer
    - OpsWorksCMServerState
    - OpsWorksInstance
    - OpsWorksLayer
    - OpsWorksUserProfile
    - RoboMakerRobotApplication
    - RoboMakerSimulationApplication
    - RoboMakerSimulationJob
    - Route53HealthCheck
    - Route53HostedZone
    - Route53ResolverEndpoint
    - Route53ResolverRule
    - Route53ResourceRecordSet
    - Route53TrafficPolicy
    - S3AccessPoint
    - S3Bucket
    - S3MultipartUpload
    - S3Object
    - EC2VPC
    - EC2Subnet
    - EC2VPCEndpoint
    - EC2RouteTable
    - EC2DefaultSecurityGroupRule
    - EC2SecurityGroup
    - CognitoUserPool
    - EC2DHCPOption
    - EC2InternetGateway

filters:
  ".*":
    - property: Name
      type: regex
      value: "^ce-grp-.*"
